import JSZip from 'jszip'
import type { DesignBrief } from './types'
import { slugify } from './slug'

// The generated component isn't guaranteed to have a default export (the
// research prompt doesn't enforce a function name) — same assumption
// ComponentPreview.tsx makes for the Sandpack wrapper, but detected instead
// of hardcoded to "App".
function ensureDefaultExport(code: string): string {
  if (/export\s+default/.test(code)) return code
  const match = code.match(/(?:function|const)\s+([A-Z]\w*)/)
  const name = match ? match[1] : 'App'
  return `${code}\nexport default ${name};`
}

// Bundles the generated component into a minimal, runnable Vite + React +
// TypeScript project and downloads it as a zip. Tailwind is loaded via CDN
// script in index.html (the same trick ComponentPreview.tsx uses for the
// Sandpack preview) so the scaffold renders correctly with zero build
// configuration — no PostCSS/Tailwind version to keep in sync.
export async function exportProject(componentCode: string, brief: DesignBrief | null) {
  const name = brief ? slugify(brief.niche || brief.industry) : 'vibeui-project'
  const title = brief ? `${brief.industry} — ${brief.niche}` : 'VibeUI component'
  const appCode = ensureDefaultExport(componentCode)

  const zip = new JSZip()

  zip.file(
    'package.json',
    JSON.stringify(
      {
        name,
        private: true,
        version: '0.1.0',
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview',
        },
        dependencies: {
          react: '^19.2.4',
          'react-dom': '^19.2.4',
          // The generated component is instructed to be import-free, but
          // include these as a safety net in case it still reaches for an
          // icon library — otherwise `npm install` would leave it broken.
          '@heroicons/react': '^2.2.0',
          'lucide-react': '^0.469.0',
        },
        devDependencies: {
          '@vitejs/plugin-react': '^4.3.4',
          typescript: '^5.7.3',
          vite: '^6.0.7',
        },
      },
      null,
      2
    )
  )

  zip.file(
    'vite.config.ts',
    `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})
`
  )

  zip.file(
    'tsconfig.json',
    JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2020',
          useDefineForClassFields: true,
          lib: ['ES2020', 'DOM', 'DOM.Iterable'],
          module: 'ESNext',
          skipLibCheck: true,
          moduleResolution: 'bundler',
          allowImportingTsExtensions: true,
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: 'react-jsx',
          strict: true,
        },
        include: ['src'],
      },
      null,
      2
    )
  )

  zip.file(
    'index.html',
    `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
    <!-- Tailwind via CDN so this runs with zero build config -->
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`
  )

  zip.file(
    'src/main.tsx',
    `import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
`
  )

  zip.file('src/App.tsx', appCode)

  const briefLines = brief
    ? [
        `- Industry: ${brief.industry} — ${brief.niche}`,
        `- Target user: ${brief.target_user}`,
        `- Feeling: ${brief.feeling}`,
        `- Color mood: ${brief.color_mood}`,
        `- Layout: ${brief.layout_density}`,
        `- Typography: ${brief.typography_feel}`,
      ].join('\n')
    : ''

  zip.file(
    'README.md',
    `# ${title}

Generated by [VibeUI](https://github.com/Farazkhan542/VibeUI) from this design brief:

${briefLines}

## Run it

\`\`\`bash
npm install
npm run dev
\`\`\`

Tailwind is loaded via CDN in \`index.html\`, so there's no build-config step required to see styles.
`
  )

  const blob = await zip.generateAsync({ type: 'blob' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${name}-vibeui-project.zip`
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}
